
import java.awt.Dimension;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jsoup.Connection.Method;
import org.jsoup.Connection.Response;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * main.java
 *
 * Created on Sep 5, 2014, 3:06:42 AM
 */
/**
 *
 * @author Kanishka
 */
public class main extends javax.swing.JFrame {

    final JFileChooser folder_chooser = new JFileChooser();
    File chosen_file = null;
    Date files_after = null;
    boolean update_date = true;
    boolean hide_date = true;
    boolean tags_disabled = true;
    boolean share_disabled = true;
    public String username = null;
    public String password = null;
    public static Map<String, String> tags = new HashMap<String, String>();

    /** Creates new form main */
    public main() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        auth = new javax.swing.JDialog();
        auth_lbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        nick_input = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        pass_input = new javax.swing.JPasswordField();
        error_lbl = new javax.swing.JLabel();
        error = new javax.swing.JOptionPane();
        about = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        title_lbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        choose_btn = new javax.swing.JButton();
        folder_chosen_lbl = new javax.swing.JLabel();
        folder_display = new javax.swing.JLabel();
        clear_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        file_list = new javax.swing.JTextArea();
        date_modified_lbl = new javax.swing.JLabel();
        DD_set = new javax.swing.JTextField();
        DD_lbl = new javax.swing.JLabel();
        MM_set = new javax.swing.JTextField();
        MM_lbl = new javax.swing.JLabel();
        YY_set = new javax.swing.JTextField();
        YY_lbl = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();
        files_found_lbl = new javax.swing.JLabel();
        files_counter = new javax.swing.JLabel();
        tags_panel = new javax.swing.JPanel();
        movie_check = new javax.swing.JCheckBox();
        tv_check = new javax.swing.JCheckBox();
        books_check = new javax.swing.JCheckBox();
        games_check = new javax.swing.JCheckBox();
        anime_check = new javax.swing.JCheckBox();
        music_check = new javax.swing.JCheckBox();
        software_check = new javax.swing.JCheckBox();
        videos_check = new javax.swing.JCheckBox();
        courses_check = new javax.swing.JCheckBox();
        apps_check = new javax.swing.JCheckBox();
        misc_check = new javax.swing.JCheckBox();
        update_tags = new javax.swing.JButton();
        share_btn = new javax.swing.JButton();
        auth_btn = new javax.swing.JButton();
        main_menu = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        exit_item = new javax.swing.JMenuItem();
        menu_about = new javax.swing.JMenu();

        auth.setTitle("Authentication");
        auth.setModal(true);
        auth.setResizable(false);

        auth_lbl.setFont(new java.awt.Font("Dialog", 1, 18));
        auth_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auth_lbl.setText("Enter DC Login Details");

        jLabel1.setText("DC Nick");

        jLabel2.setText("DC Password");

        login_btn.setText("LOGIN");
        login_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btnMouseClicked(evt);
            }
        });

        reset_btn.setText("RESET");
        reset_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_btnMouseClicked(evt);
            }
        });

        pass_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        error_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error_lbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout authLayout = new javax.swing.GroupLayout(auth.getContentPane());
        auth.getContentPane().setLayout(authLayout);
        authLayout.setHorizontalGroup(
            authLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(auth_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
            .addGroup(authLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(authLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nick_input, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(authLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(authLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(reset_btn)
                .addContainerGap())
            .addGroup(authLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pass_input, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(authLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(error_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );
        authLayout.setVerticalGroup(
            authLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(auth_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nick_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(authLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_btn)
                    .addComponent(reset_btn))
                .addGap(18, 18, 18)
                .addComponent(error_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        about.setTitle("About");
        about.setResizable(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("DC Hub AutoShare");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Conceived and Designed By");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" Kanishka Ganguly");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Special Thanks To");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Koushik MLN");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("DC Hub AutoShare allows you to automatically share all files after a specified date on your DC account.\nThe main reason for this is that people share files on DC but forget to (or are too lazy to) publish that fact on the chat or on their accounts.\nThis app takes care of that by automatically scanning your folder for new files and posting them on DC.\nThis allows people to know that you have shared new files.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout aboutLayout = new javax.swing.GroupLayout(about.getContentPane());
        about.getContentPane().setLayout(aboutLayout);
        aboutLayout.setHorizontalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
            .addGroup(aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(aboutLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel5)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(80, 80, 80))
            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
            .addGroup(aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        aboutLayout.setVerticalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DC AutoShare");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        title_lbl.setFont(new java.awt.Font("Dialog", 1, 24));
        title_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_lbl.setText("DC Hub AutoShare");

        choose_btn.setText("Choose Folder");
        choose_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choose_btnMouseClicked(evt);
            }
        });

        folder_chosen_lbl.setText("Folder Chosen:");

        folder_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        folder_display.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        clear_btn.setText("Clear Folder");
        clear_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_btnMouseClicked(evt);
            }
        });

        file_list.setColumns(20);
        file_list.setRows(5);
        jScrollPane1.setViewportView(file_list);

        date_modified_lbl.setText("Show Files After:");

        DD_set.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        DD_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DD_lbl.setText("DD");

        MM_set.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        MM_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MM_lbl.setText("MM");

        YY_set.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        YY_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YY_lbl.setText("YY");

        update_btn.setText("UPDATE FILES");
        update_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_btnMouseClicked(evt);
            }
        });

        files_found_lbl.setText("Files Found:");

        files_counter.setFont(new java.awt.Font("Dialog", 1, 12));
        files_counter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        files_counter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tags_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose Tags"));

        movie_check.setText("Movies");

        tv_check.setText("TV Series");

        books_check.setText("Books");

        games_check.setText("Games");

        anime_check.setText("Anime");

        music_check.setText("Music");

        software_check.setText("Software");

        videos_check.setText("Videos");

        courses_check.setText("Video Courses");

        apps_check.setText("Mobile Apps");

        misc_check.setText("Miscellaneous");

        update_tags.setText("UPDATE TAGS");
        update_tags.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_tagsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tags_panelLayout = new javax.swing.GroupLayout(tags_panel);
        tags_panel.setLayout(tags_panelLayout);
        tags_panelLayout.setHorizontalGroup(
            tags_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tags_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tags_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movie_check)
                    .addComponent(tv_check)
                    .addComponent(books_check))
                .addGap(20, 20, 20)
                .addGroup(tags_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tags_panelLayout.createSequentialGroup()
                        .addGroup(tags_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(games_check)
                            .addComponent(anime_check))
                        .addGap(18, 18, 18)
                        .addGroup(tags_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(software_check)
                            .addComponent(videos_check)))
                    .addGroup(tags_panelLayout.createSequentialGroup()
                        .addComponent(music_check)
                        .addGap(18, 18, 18)
                        .addComponent(courses_check, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tags_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(misc_check)
                    .addComponent(apps_check)
                    .addComponent(update_tags))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tags_panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {anime_check, books_check, games_check, movie_check, music_check, software_check, tv_check, videos_check});

        tags_panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {apps_check, courses_check, misc_check});

        tags_panelLayout.setVerticalGroup(
            tags_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tags_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tags_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movie_check)
                    .addComponent(games_check)
                    .addComponent(software_check)
                    .addComponent(apps_check))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tags_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tv_check)
                    .addComponent(anime_check)
                    .addComponent(videos_check)
                    .addComponent(misc_check))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tags_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(books_check)
                    .addComponent(music_check)
                    .addComponent(courses_check)
                    .addComponent(update_tags)))
        );

        share_btn.setText("SHARE NOW");
        share_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                share_btnMouseClicked(evt);
            }
        });

        auth_btn.setText("AUTHENTICATE");
        auth_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                auth_btnMouseClicked(evt);
            }
        });

        menu_file.setText("File");

        exit_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exit_item.setText("Exit");
        exit_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_itemMouseClicked(evt);
            }
        });
        menu_file.add(exit_item);

        main_menu.add(menu_file);

        menu_about.setText("About");
        menu_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_aboutMouseClicked(evt);
            }
        });
        main_menu.add(menu_about);

        setJMenuBar(main_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(folder_chosen_lbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(choose_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addComponent(clear_btn))
                    .addComponent(folder_display, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_modified_lbl)
                    .addComponent(files_found_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DD_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DD_set, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MM_set, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MM_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(YY_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(YY_set, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(files_counter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(auth_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(update_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(title_lbl)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(share_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tags_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {choose_btn, clear_btn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DD_set, MM_set});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(folder_chosen_lbl)
                    .addComponent(folder_display, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choose_btn)
                    .addComponent(clear_btn))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_modified_lbl)
                    .addComponent(DD_set, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MM_set, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YY_set, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_btn))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DD_lbl)
                    .addComponent(MM_lbl)
                    .addComponent(YY_lbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(files_found_lbl)
                    .addComponent(files_counter, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auth_btn))
                .addGap(18, 18, 18)
                .addComponent(tags_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(share_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choose_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choose_btnMouseClicked
        folder_chooser.setApproveButtonText("Choose Folder");
        folder_chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = folder_chooser.showOpenDialog(this);
        try {
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                chosen_file = folder_chooser.getSelectedFile();
                folder_display.setText(chosen_file.getPath());
            } else {
                chosen_file = null;
                folder_display.setText("");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        hide_date = false;
        DD_set.setEnabled(true);
        MM_set.setEnabled(true);
        YY_set.setEnabled(true);
        update_btn.setEnabled(true);
    }//GEN-LAST:event_choose_btnMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        file_list.setEditable(false);
        if (update_date == true) {
            Calendar today = Calendar.getInstance();
            int YY = today.get(Calendar.YEAR);
            int MM = today.get(Calendar.MONTH);
            int DD = today.get(Calendar.DATE);
            YY_set.setText("" + YY);
            MM_set.setText("" + MM);
            DD_set.setText("" + DD);
        }
        if (hide_date == true) {
            DD_set.setEnabled(false);
            MM_set.setEnabled(false);
            YY_set.setEnabled(false);
            update_btn.setEnabled(false);
        }
        if (tags_disabled == true) {
            update_tags.setEnabled(false);
        }
        if (share_disabled == true) {
            share_btn.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowActivated

    private void clear_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_btnMouseClicked
        folder_display.setText("");
        chosen_file = null;
        file_list.setText("");
        files_counter.setText("");
    }//GEN-LAST:event_clear_btnMouseClicked

    private void update_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_btnMouseClicked
        update_date = false;
        tags_disabled = false;
        update_tags.setEnabled(true);

        int files_found = 0;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-M-yyyy");
            String date_as_string = DD_set.getText() + "-" + MM_set.getText() + "-" + YY_set.getText();
            files_after = sdf.parse(date_as_string);

            //FILE WALKER
            File[] files_in_dir = chosen_file.listFiles();
            for (File file : files_in_dir) {
                String date_modified = sdf.format(file.lastModified());
                Date file_date = sdf.parse(date_modified);
                if (file_date.after(files_after)) {
                    file_list.append(file.getName());
                    file_list.append("\n");
                    files_counter.setText("" + files_found);
                    files_found++;
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_update_btnMouseClicked

    private void update_tagsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_tagsMouseClicked
        if (videos_check.isSelected()) {
            tags.put("data[tag]", "video");
        }
        if (courses_check.isSelected()) {
            tags.put("data[tag]", "courses");
        }
        if (misc_check.isSelected()) {
            tags.put("data[tag]", "miscellaneous");
        }
        if (apps_check.isSelected()) {
            tags.put("data[tag]", "apps");
        }
        if (movie_check.isSelected()) {
            tags.put("data[movie]", "movie");
        }
        if (tv_check.isSelected()) {
            tags.put("data[tv]", "tv");
        }
        if (games_check.isSelected()) {
            tags.put("data[game]", "game");
        }
        if (books_check.isSelected()) {
            tags.put("data[book]", "book");
        }
        if (anime_check.isSelected()) {
            tags.put("data[anime]", "anime");
        }
        if (music_check.isSelected()) {
            tags.put("data[music]", "music");
        }
        if (software_check.isSelected()) {
            tags.put("data[software]", "software");
        }
    }//GEN-LAST:event_update_tagsMouseClicked

    private void login_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btnMouseClicked
        username = nick_input.getText();
        password = pass_input.getText();
        if (username == null || password == null || "".equals(username) || "".equals(password)) {
            error_lbl.setText("BLANK FIELDS?");
        } else {
            error_lbl.setText("DONE");
            share_disabled = false;
            share_btn.setEnabled(true);
            auth.dispose();
        }
    }//GEN-LAST:event_login_btnMouseClicked

    private void reset_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_btnMouseClicked
        username = null;
        password = null;
        nick_input.setText("");
        pass_input.setText("");
    }//GEN-LAST:event_reset_btnMouseClicked

    private void share_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_share_btnMouseClicked
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-M-yyyy");
            String date_as_string = DD_set.getText() + "-" + MM_set.getText() + "-" + YY_set.getText();
            files_after = sdf.parse(date_as_string);

            File[] files_in_dir = chosen_file.listFiles();
            for (File file : files_in_dir) {
                String date_modified = sdf.format(file.lastModified());
                Date file_date = sdf.parse(date_modified);
                if (file_date.after(files_after)) {
                    String title = file.getName();
                    autoshare(username, password, title);
                }
            }
            error.showMessageDialog(this, "Done Sharing", "Finished", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            error.showMessageDialog(this, "Error" + e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_share_btnMouseClicked

    private void auth_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_auth_btnMouseClicked
        Dimension size_of_auth = new Dimension(220, 320);
        auth.setMinimumSize(size_of_auth);
        auth.setVisible(true);
    }//GEN-LAST:event_auth_btnMouseClicked

    private void exit_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_itemMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exit_itemMouseClicked

    private void menu_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_aboutMouseClicked
        Dimension size_of_about = new Dimension(240, 400);
        about.setMinimumSize(size_of_about);
        about.setVisible(true);
    }//GEN-LAST:event_menu_aboutMouseClicked

    public static void autoshare(String username, String password, String title) {
        tags.put("data[title]", title);
        tags.put("share", "Share");
        try {
            Response res = Jsoup.connect("http://172.16.32.222/dchub/process.php").data(
                    "data[username]", username,
                    "data[password]", password,
                    "data[remme]", "on",
                    "login", "Sign In").method(Method.POST).execute();
            Map<String, String> loginCookies = res.cookies();
            System.out.println(loginCookies.get("PHPSESSID"));
            Document doc = Jsoup.connect("http://172.16.32.222/dchub/").cookies(loginCookies).get();
            Response res2 = Jsoup.connect("http://172.16.32.222/dchub/process.php").cookie("PHPSESSID", loginCookies.get("PHPSESSID")).data(
                    tags).method(Method.POST).execute();
            //System.out.println(res2.statusCode() + " " + res2.statusMessage());
            //System.out.println(res2.body());
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DD_lbl;
    private javax.swing.JTextField DD_set;
    private javax.swing.JLabel MM_lbl;
    private javax.swing.JTextField MM_set;
    private javax.swing.JLabel YY_lbl;
    private javax.swing.JTextField YY_set;
    private javax.swing.JDialog about;
    private javax.swing.JCheckBox anime_check;
    private javax.swing.JCheckBox apps_check;
    private javax.swing.JDialog auth;
    private javax.swing.JButton auth_btn;
    private javax.swing.JLabel auth_lbl;
    private javax.swing.JCheckBox books_check;
    private javax.swing.JButton choose_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JCheckBox courses_check;
    private javax.swing.JLabel date_modified_lbl;
    private javax.swing.JOptionPane error;
    private javax.swing.JLabel error_lbl;
    private javax.swing.JMenuItem exit_item;
    private javax.swing.JTextArea file_list;
    private javax.swing.JLabel files_counter;
    private javax.swing.JLabel files_found_lbl;
    private javax.swing.JLabel folder_chosen_lbl;
    private javax.swing.JLabel folder_display;
    private javax.swing.JCheckBox games_check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton login_btn;
    private javax.swing.JMenuBar main_menu;
    private javax.swing.JMenu menu_about;
    private javax.swing.JMenu menu_file;
    private javax.swing.JCheckBox misc_check;
    private javax.swing.JCheckBox movie_check;
    private javax.swing.JCheckBox music_check;
    private javax.swing.JTextField nick_input;
    private javax.swing.JPasswordField pass_input;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton share_btn;
    private javax.swing.JCheckBox software_check;
    private javax.swing.JPanel tags_panel;
    private javax.swing.JLabel title_lbl;
    private javax.swing.JCheckBox tv_check;
    private javax.swing.JButton update_btn;
    private javax.swing.JButton update_tags;
    private javax.swing.JCheckBox videos_check;
    // End of variables declaration//GEN-END:variables
}
